### ISSUE TITLE
it does not work in react native

### ISSUE THREAD

**Issue by sibelius** [rsdoiel/mimetype-js#10]
I have this error when trying to use this module in my react native package

Unable to resolve module path from /node_modules/mime-types/index.js: MOdule does not exist in the module map

**Comment by sibelius** [comment]
this make it work: https://github.com/Liroo/react-native-mime-types/commit/60696d08c507828485909da3973937ff0316d7da

**Comment by sibelius** [comment]
@Liroo do u think it is worth send a PR to this package?

**Comment by Liroo** [comment]
Maybe it's worth it to keep my git hub, but I will do some test if my own fork is compatible with the original repository :) 🚀

**Comment by rsdoiel** [comment]
Hello, I rarely write NodeJS/npm code these days so am not up on the current practices.  I have never written anything requiring React so do not know that is requires.  Sorry for my ignorance.  This package was written back when NodeJS was young Ryan Dahl was still very much involved.  

From your description I would guess that React is looking for index.js exclusively to know what to pull in to its system.  You could try symbolically linking mimetype.js (or renaming) to index.js and see if that works.

**Comment by Liroo** [comment]
The fact is there is no `path` module on react-native, I recode a basic `path.extname` for compatibility

**Comment by rsdoiel** [comment]
Sounds good. Feel free to send a pull request, if this is something that will help others. All the best Robert
