### ISSUE TITLE
Please add a license file  

### ISSUE THREAD

**Issue by eyaleizenberg** [rsdoiel/mimetype-js#8]
I assume this is MIT?

**Comment by rsdoiel** [comment]
I usually use the BSD 2-clause. I've added a file to the respository. Thank you for pointing out that it was missing I had missed that.  

All the best,

Robert

**Comment by eyaleizenberg** [comment]
Your package.json is also missing it ;)

Thanks

**Comment by rsdoiel** [comment]
Fixed that and after several false starts bumped the version number and pushed the update to npm.
